# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: end-of-file-fixer
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: (?x)(tests/|pixl/defaults.py|README.md|locales/)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.243'
    hooks:
      - id: ruff
        args: [--fix]
